execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set expandtab
let g:vim_markdown_folding_disabled=1
let g:pymode_folding = 0
let g:pymode_lint = 0
filetype indent on
