# Display COMMUNISM on first tab of each new window
if [[ $ITERM_SESSION_ID == *"t0"* &&
      $ITERM_PROFILE == "SUMMONING BOWLS" && 
      `hostname` != "moloch.local" ]]; then
  imgcat ~/dotfiles/zsh/hs.gif
fi
