source ~/.zgen.zsh

if ! zgen saved; then
  zgen prezto editor key-bindings 'emacs'

  zgen load "$HOME/dotfiles/zsh/themes/huh/prompt_huh_setup"
  zgen prezto prompt theme 'huh'
  zgen prezto '*:*' case-sensitive 'yes'
  zgen prezto '*:*' color 'yes'

  zgen prezto
  zgen prezto git
  zgen prezto history-substring-search
  zgen prezto command-not-found
  zgen prezto syntax-highlighting

  zgen load zsh-users/zsh-syntax-highlighting
  zgen load tarruda/zsh-autosuggestions

  if [[ `uname` == 'Darwin' ]]; then
    zgen prezto homebrew
    zgen prezto osx
  fi
fi

#unalias rm
. ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
. ~/.zsh_aliases
eval "$(thefuck --alias)"

if [[ `uname` == 'Darwin' ]]; then
  test -e "${HOME}/.iterm2_shell_integration.zsh" &&\
    source "${HOME}/.iterm2_shell_integration.zsh"
  alias restartaudio="sudo killall coreaudiod"
  test -e "/Applications/Emacs.app/Contents/MacOS/Emacs" &&\
    alias emacs=/Applications/Emacs.app/Contents/MacOS/Emacs
fi

eval `opam config env`
. /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
